leanovate/play-mockws

src/main/scala/mockws/MockWS.scala, src/test/scala/mockws/MockWSTest.scala
With this PR, `ws.withMethod(method)` is supported, and specified method is used in `ws.execute()` and `ws.stream()`. Like with `NingWSClient`, default method is `GET`.
=> add support for withMethod in execute and stream

src/main/scala/mockws/MockWS.scala
added support in WSMock  for :
* retrieving allHeaders on response 
*for getResponseBodyAsBytes on underlying response
=> support for allHeaders + getResponseBodyAsBytes

.travis.yml, build.sbt, src/main/scala/mockws/FakeAhcResponse.scala, src/main/scala/mockws/FakeWSRequestHolder.scala, src/main/scala/mockws/FakeWSResponseHeaders.scala, src/main/scala/mockws/MockWS.scala, src/main/scala/mockws/TimeoutProvider.scala, src/test/scala/mockws/CookieTest.scala, src/test/scala/mockws/FakeAchResponseTest.scala, src/test/scala/mockws/ResponseHeaderTest.scala, src/test/scala/mockws/TimeoutTest.scala
> Implementing WSRequest instead of using a mock would ensure that we do not forget any methods.
It is a good idea, but quite a rewrite of the actual code.
This PR resolves #8 by replacing mockito with a concrete implementation. MockWS definitely will not produce NPEs from missing stubs anymore!
I added a bit more test coverage and also implemented request timeouts. All existing tests pass locally without any modification.
=> Replace mockito with a concrete implementation.

src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/MockWSTest.scala
A `Result.body.dataStream` is a `Source[ByteString, _]` which generates
a stream of ByteString elements.
Using a `Sink.headOption` in runWith only processes the first (optional)
element and ignores all subsequent elements.
When using a MockWS with `Ok.sendFile` in a specification, the
controller using the `WSRequest` only received the first 8192 Bytes of
the given file because of this.
Concatenate all generated `ByteString`s and use that as responseBody.
=> Fix truncated response in FakeWSRequestHolder

src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/MockWSTest.scala
This PR enables usage of `withAuth` on `MockWS` object.
The 'Authorization' header is set according to RFC 2617,
Section 2 [1] 'Basic Authentication Scheme'.
Other schemata are not supported.
The (positive) test case is based on work of @Manc and
implementation of @yanns [2].
[1] https://tools.ietf.org/html/rfc2617#section-2
[2] https://github.com/leanovate/play-mockws/issues/12#issuecomment-204978719
=> add support for HTTP Authentication: Basic - Fixes #12

README.md, src/main/scala/mockws/MockWSHelpers.scala, src/test/scala/mockws/AuthenticationTest.scala, src/test/scala/mockws/Example.scala, src/test/scala/mockws/FakeAchResponseTest.scala, src/test/scala/mockws/MockWSTest.scala, src/test/scala/mockws/ResponseHeaderTest.scala, src/test/scala/mockws/RouteTest.scala, src/test/scala/mockws/StreamingTest.scala, src/test/scala/mockws/TimeoutTest.scala
The shutdown hook should only be used when using the helpers objects.
The helpers trait provide a shutdown function that can be used
by after all hook from test frameworks.
=> No shutdown hook when using trait

README.md
Currently, README is very confusing, because 2.6.0 doesn't have `MockWSHelpers`, better update docs to mention the latest version.
=> Update README.md: latest version is 2.6.2

src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/MockWSTest.scala
When calling this method old headers are discarded
Here's a corresponding test in play-ws: https://github.com/playframework/play-ws/blob/master/play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala#L212
=> Fix withHttpHeaders behavior for FakeWSRequestHolder

src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/MockWSTest.scala
When calling this method old query parameters are discarded
Test in play-ws: https://github.com/playframework/play-ws/blob/b212e73188b894fd474522e5dd7773feab164a89/play-ahc-ws-standalone/src/test/scala/play/api/libs/ws/ahc/AhcWSRequestSpec.scala#L67
=> Fix withQueryStringParameters behavior for FakeWSRequestHolder

src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/MockWSTest.scala
This fixes a regression introduced in commit
26aec991f50a7226dc4df76495dd546a8045b712 after which `withHttpHeaders` discards
old headers.
This causes all headers to vanish if you sent a body with the request.
=> Use `addHttpHeaders` in `withBodyAndContentType`

src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/AuthenticationTest.scala
I believe there shouldn't be a colon after `Basic` in the auth header
=> Remove colon after 'Basic' in basic auth

src/main/scala/mockws/FakeWSRequestHolder.scala, src/main/scala/mockws/MockWS.scala, src/test/scala/mockws/MockWSTest.scala
If there is no route, that means the future is successful but the server returned 404
If we think of it as an exception with failed future then it will suppress the semantics of
client failure vs HTTP failures. Caller should check for HTTP status rather than future state
=> return 404 for route not found

src/main/scala/mockws/FakeWSResponseHeaders.scala
Given the documentation discusses a Seq of size 1 I'm assuming the correction to avoid confusion is to remove the additional `"` and make the Seq a valid single string rather than adding an additional `"` and making it 2 strings?
=> Correct typo in documentation

.travis.yml, build.sbt, project/plugins.sbt
After I did open #90 against the original update_scala_versions branch accidentally, let's try it against master this time... :wink: 
Close #84
=> Update scala versions

.scalafmt.conf, build.sbt, src/test/scala/mockws/MockWSTest.scala
This PR supersedes #117 which upgrades scalafmt to version 2.5.2 and also re-configures and reformats the sources accordingly.
I tried to configure scalafmt to adhere to the current style as much as possible in order to minimize the changes done by running scalafmt.
Close #117, close #116
=> Update scalafmt-core to 2.5.2

src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/RequestFilterTest.scala
I assume it was simply some kind of laziness that the request filter functionality is not implemented currently.
Fixes #149
=> Support request filters

.github/workflows/ci.yml, README.md, RELEASE-NOTES.md, build.sbt, project/build.properties, src/main/scala/mockws/FakeWSRequestHolder.scala, src/test/scala/mockws/AuthenticationTest.scala, src/test/scala/mockws/Example.scala, src/test/scala/mockws/MockWSTest.scala, src/test/scala/mockws/StreamingTest.scala, version.sbt
Play 2.9 was just released, this PR bumps `play-mockws` to the newest version. Play 3.x has also just been released but will involve some breaking changes, figure some people might have some benefit to having a Play 2.9 version of this library before then.
Tests ran against Scala 2.13 and Scala 3 with:
`sbt ++3.3.1! test`
`sbt ++2.13.1! test`
=> Play 2.9 & Scala 3

build.sbt
Add relocation details to the published POM before we merge https://github.com/leanovate/play-mockws/pull/335.
This way, users may be able to see the new coordinates in some tools like mvnrepository.com.
=> 🏗️ build: add relocation details to Maven POM

build.sbt
Since https://github.com/leanovate/play-mockws/pull/335, the publish workflow was broken.
=> 📦 ci: fix publish settings

build.sbt, project/plugins.sbt
Supersedes https://github.com/leanovate/play-mockws/pull/556
This will be merged as an attempt to see if we can publish without using `sonatypeProfileName` with Central Portal maybe. If not, I'll revert.
=> chore(deps): update dependency com.github.sbt:sbt-ci-release to v1.11.0

README.md
* use Central Sonatype compatible URL
* use img.shields.io directly instead of https://maven-badges.herokuapp.com or https://maven-badges.sml.io
=> docs: update maven badge

RELEASE-NOTES.md, build.sbt
Fixes wrong update by Scala Steward https://github.com/leanovate/play-mockws/pull/590
=> 🧹 chore: upgrade Play to 3.0.9
